apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-monitoring
  namespace: monitoring 
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ingress.allow-http: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: prometheus.bmijrwbbk2uh.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-k8s
            port:
              number: 9090
  # - host: alertcenter.bmijrwbbk2uh.com
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: prometheus-alert-center
  #           port:
  #             number: 8080
                # - host: alertmanager.bmijrwbbk2uh.com
                #   http:
                #     paths:
                #     - path: /
                #       pathType: Prefix
                #       backend:
                #         service:
                #           name: alertmanager-main
                #           port:
                #             number: 9093
                # - host: grafana.bmijrwbbk2uh.com
                #   http:
                #     paths:
                #     - path: /
                #       pathType: Prefix
                #       backend:
                #         service:
                #           name: grafana
                #           port:
                #             number: 3000
